[build]
  # Directory to publish (Hugo outputs to 'public' by default)
  publish = "public"
  # Command to build your Hugo site
  command = "hugo"

[build.environment]
  # Set Hugo version explicitly for Netlify's build image
  HUGO_VERSION = "0.125.4"

[context.production.environment]
  # Optional: Enable minification, set baseURL for production
  HUGO_ENV = "production"
  HUGO_BASEURL = "https://peppy-phoenix-9d0777.netlify.app/"  # <-- Replace with your actual URL

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200