name: github pages

on:
  repository_dispatch:
    types: [start-workflow]
  pull_request:
  schedule:
    - cron: '0 9 * * *'

jobs:
  cloudflare_production_deploy:
    if: github.event_name == 'repository_dispatch' && github.event.action == 'start-workflow'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch and checkout master
        run: |
          git fetch origin master
          git checkout master

      - name: Create empty commit to trigger Cloudflare deploy
        run: |
          git commit --allow-empty -m "Trigger Cloudflare Pages production deploy"
          git push origin master

  build_and_deploy:
    if: github.event_name != 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Checkout branch from dispatch payload
        if: github.event.client_payload.branch != ''
        run: |
          git fetch origin ${{ github.event.client_payload.branch }}
          git checkout ${{ github.event.client_payload.branch }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.1'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
