name: github pages

on:
  repository_dispatch:
    types: [start-workflow]
  pull_request:
  schedule:
    # 8:00 AM UTC - 4 hours = 4:00 AM Eastern Daylight Time (EDT)
    - cron: '0 8 * * *'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.1'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Trigger Cloudflare Pages production deploy
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin master
          git checkout master
          git commit --allow-empty -m "Trigger Cloudflare Pages production deploy"
          git push origin master
